stainless-dotty\
 src/main/scala/ch/epfl/lexer/VerifiedRegex.scala\
 src/main/scala/ch/epfl/lexer/VerifiedLexer.scala\
 src/main/scala/ch/epfl/lexer/Utils.scala\
 src/main/scala/ch/epfl/lexer/LexerInterface.scala\
 src/main/scala/ch/epfl/map/*\
 src/main/scala/ch/epfl/example/AmyLexer.scala\
 src/main/scala/ch/epfl/example/PythonLexer.scala\
 src/main/scala/ch/epfl/example/JSONLexer.scala\
 src/main/scala/ch/epfl/example/JsonManipulation.scala\
 src/main/scala/ch/epfl/example/Utils.scala\
 src/main/scala/ch/epfl/lexer/Vector.scala\
 --config-file=stainless.conf\
 -D-parallel=16\
 $1
