stainless-dotty\
 src/main/scala/com/ziplex/lexer/VerifiedRegex.scala\
 src/main/scala/com/ziplex/lexer/VerifiedLexer.scala\
 src/main/scala/com/ziplex/lexer/Utils.scala\
 src/main/scala/com/ziplex/lexer/LexerInterface.scala\
 src/main/scala/com/ziplex/map/*\
 src/main/scala/com/ziplex/example/AmyLexer.scala\
 src/main/scala/com/ziplex/example/PythonLexer.scala\
 src/main/scala/com/ziplex/example/JSONLexer.scala\
 src/main/scala/com/ziplex/example/JsonManipulation.scala\
 src/main/scala/com/ziplex/example/Utils.scala\
 src/main/scala/com/ziplex/lexer/Vector.scala\
 --config-file=stainless.conf\
 -D-parallel=16\
 $1
