name: Bolts CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: [self-hosted, linux]
    steps:
    - name: Setup
      uses: ./.github/workflows/setup.yml
    - name: Checkout
      uses: actions/checkout@v4
    - name: Bolts Tests
      run: ./run-tests.sh --admit-vcs
  fail_if_pull_request_is_draft:
    if: github.event.pull_request.draft == true
    runs-on: [self-hosted, linux]
    steps:
    - name: Fails in order to indicate that pull request needs to be marked as ready to review and tests workflows need to pass.
      run: exit 1